import type {
  IncidentSignal,
  NormalizedIssue,
  PriorityScore,
  EnrichedContext,
  ResponsePlan,
  AlertDraft,
  ImpactSummary,
} from "../schemas";

// ─── Demo Scenario Presets ───

export const SCENARIO_PRESETS = [
  {
    id: "heatwave-water",
    name: "Heatwave + Water Shortage",
    description: "Rising temperatures stress the water grid and endanger vulnerable residents.",
  },
  {
    id: "flood-traffic",
    name: "Flooding + Traffic Disruption",
    description: "Flash flood warnings combined with major traffic chokepoints.",
  },
  {
    id: "blackout-medical",
    name: "Campus Blackout + Medical Urgency",
    description: "Power failure across a campus with a medical facility dependent on electricity.",
  },
] as const;

// ─── Seed Signals ───

const heatwaveWaterSignals: IncidentSignal[] = [
  {
    id: "sig-001",
    source: "weather-feed",
    category: "heat-stress",
    title: "Extreme Heat Advisory",
    description: "Temperatures exceeding 108°F forecast for 48 hours. Heat index 115°F. Vulnerable populations at severe risk.",
    location: "Metro District 7 – Oakridge Neighborhood",
    coordinates: { lat: 33.749, lng: -84.388 },
    reportedAt: new Date(Date.now() - 1800000).toISOString(),
    populationAffected: 12400,
    serviceCriticality: 8,
  },
  {
    id: "sig-002",
    source: "service-status",
    category: "water-outage",
    title: "Water Main Pressure Drop",
    description: "Water pressure dropped 60% in zones 4A and 4B. Aging infrastructure failing under heat load. Estimated 8,000 households affected.",
    location: "Zone 4A/4B – Maple Street Corridor",
    coordinates: { lat: 33.751, lng: -84.392 },
    reportedAt: new Date(Date.now() - 3600000).toISOString(),
    populationAffected: 8200,
    serviceCriticality: 10,
  },
  {
    id: "sig-003",
    source: "manual-report",
    category: "waste-buildup",
    title: "Garbage Collection Delayed",
    description: "Scheduled pickup missed for 2 consecutive days. Overflowing bins attracting pests. Odor complaints rising.",
    location: "Riverside Apartments – Block C",
    coordinates: { lat: 33.755, lng: -84.385 },
    reportedAt: new Date(Date.now() - 7200000).toISOString(),
    populationAffected: 320,
    serviceCriticality: 3,
  },
  {
    id: "sig-004",
    source: "complaint-log",
    category: "traffic-chokepoint",
    title: "Construction Blocking Main Artery",
    description: "Unscheduled utility work blocking 2 lanes on Broad Street. Rush hour delays averaging 35 minutes.",
    location: "Broad Street & 5th Avenue",
    coordinates: { lat: 33.748, lng: -84.390 },
    reportedAt: new Date(Date.now() - 5400000).toISOString(),
    populationAffected: 4500,
    serviceCriticality: 4,
  },
  {
    id: "sig-005",
    source: "weather-feed",
    category: "power-cut",
    title: "Transformer Overload Warning",
    description: "Grid load approaching 95% capacity. Rolling brownouts likely within 6 hours if demand continues.",
    location: "District 7 Power Substation",
    coordinates: { lat: 33.750, lng: -84.387 },
    reportedAt: new Date(Date.now() - 2400000).toISOString(),
    populationAffected: 15000,
    serviceCriticality: 9,
  },
];

const floodTrafficSignals: IncidentSignal[] = [
  {
    id: "sig-010",
    source: "weather-feed",
    category: "flooding",
    title: "Flash Flood Warning",
    description: "Creek overflow imminent. Water levels 2 feet above flood stage. Low-lying areas will flood within 2 hours.",
    location: "Willow Creek Basin – Residential Zone",
    coordinates: { lat: 34.052, lng: -118.243 },
    reportedAt: new Date(Date.now() - 1200000).toISOString(),
    populationAffected: 3100,
    serviceCriticality: 9,
  },
  {
    id: "sig-011",
    source: "manual-report",
    category: "traffic-chokepoint",
    title: "Highway 101 Underpass Flooding",
    description: "Standing water 18 inches deep. Both directions impassable. Emergency detour needed.",
    location: "Highway 101 at Cedar Blvd",
    coordinates: { lat: 34.050, lng: -118.248 },
    reportedAt: new Date(Date.now() - 900000).toISOString(),
    populationAffected: 8000,
    serviceCriticality: 8,
  },
  {
    id: "sig-012",
    source: "complaint-log",
    category: "waste-buildup",
    title: "Storm Debris Blocking Sidewalks",
    description: "Fallen branches and trash accumulating after initial storm surge. Accessibility impaired for disabled residents.",
    location: "Elm Street – Blocks 3-7",
    coordinates: { lat: 34.053, lng: -118.241 },
    reportedAt: new Date(Date.now() - 4800000).toISOString(),
    populationAffected: 600,
    serviceCriticality: 4,
  },
  {
    id: "sig-013",
    source: "service-status",
    category: "power-cut",
    title: "Intermittent Power in East Wing",
    description: "Power flickering every 15 minutes. Sensitive equipment at risk. Hospital backup generators on standby.",
    location: "East District – Medical Campus",
    coordinates: { lat: 34.049, lng: -118.245 },
    reportedAt: new Date(Date.now() - 2100000).toISOString(),
    populationAffected: 5200,
    serviceCriticality: 9,
  },
];

const blackoutMedicalSignals: IncidentSignal[] = [
  {
    id: "sig-020",
    source: "service-status",
    category: "power-cut",
    title: "Campus-Wide Blackout",
    description: "Complete power failure across North Campus. Main switchgear failure. No ETA for restoration. Backup power limited to 4 hours.",
    location: "North Campus – All Buildings",
    coordinates: { lat: 42.360, lng: -71.094 },
    reportedAt: new Date(Date.now() - 600000).toISOString(),
    populationAffected: 9500,
    serviceCriticality: 10,
  },
  {
    id: "sig-021",
    source: "manual-report",
    category: "medical-urgency",
    title: "Dialysis Center on Backup Power",
    description: "12 patients mid-treatment when power failed. Backup generators active but fuel limited to 3 hours. Immediate patient transfer needed.",
    location: "Health Sciences Building – Dialysis Unit",
    coordinates: { lat: 42.361, lng: -71.092 },
    reportedAt: new Date(Date.now() - 480000).toISOString(),
    populationAffected: 12,
    serviceCriticality: 10,
  },
  {
    id: "sig-022",
    source: "complaint-log",
    category: "water-outage",
    title: "Water Pump Failure",
    description: "Elevator pumps and water circulation pumps non-functional. Multiple buildings without water pressure above 3rd floor.",
    location: "Student Housing Blocks A-D",
    coordinates: { lat: 42.359, lng: -71.096 },
    reportedAt: new Date(Date.now() - 1500000).toISOString(),
    populationAffected: 2200,
    serviceCriticality: 7,
  },
  {
    id: "sig-023",
    source: "weather-feed",
    category: "heat-stress",
    title: "HVAC Systems Down",
    description: "Indoor temperatures rising 3°F per hour in dormitories. Elderly summer program participants at risk.",
    location: "Summer Housing – Thompson Hall",
    coordinates: { lat: 42.362, lng: -71.091 },
    reportedAt: new Date(Date.now() - 1200000).toISOString(),
    populationAffected: 450,
    serviceCriticality: 6,
  },
];

export const ALL_SIGNALS: Record<string, IncidentSignal[]> = {
  "heatwave-water": heatwaveWaterSignals,
  "flood-traffic": floodTrafficSignals,
  "blackout-medical": blackoutMedicalSignals,
};

// ─── Enriched Contexts (pre-generated for demo) ───

export const DEMO_ENRICHED_CONTEXTS: Record<string, EnrichedContext[]> = {
  "heatwave-water": [
    {
      issueId: "sig-002",
      whyItMatters: "Clean drinking water is a life-sustaining necessity. With temperatures exceeding 108°F, dehydration risk is extreme. A 60% pressure drop means many households have no running water at all.",
      whoIsAffected: "8,200 households in zones 4A and 4B, including 1,200 elderly residents and 800 families with young children who are most vulnerable to dehydration.",
      likelyNextImpact: "If not addressed within 2 hours, the pressure drop will become a full outage. Emergency services will be overwhelmed with heat-related calls. Boil-water advisory likely.",
      urgencyExplanation: "Water infrastructure failure during extreme heat creates a compounding crisis. Every hour without water increases emergency room visits exponentially.",
      recommendation: "Deploy emergency water distribution points immediately. Activate mutual aid with neighboring districts. Issue boil-water advisory proactively.",
    },
    {
      issueId: "sig-001",
      whyItMatters: "Temperatures of 108°F with a heat index of 115°F exceed the body's ability to cool itself. This is a life-threatening situation for vulnerable populations.",
      whoIsAffected: "12,400 residents, with highest risk to elderly (2,100), outdoor workers (3,400), and homeless individuals (estimated 200).",
      likelyNextImpact: "Without intervention, heat-related emergency calls will spike 300-500% within 6 hours. Power grid strain will trigger rolling brownouts.",
      urgencyExplanation: "Heat stress is a silent killer. By the time people call for help, they may already be in medical crisis.",
      recommendation: "Open cooling centers immediately. Deploy wellness checks for elderly residents. Coordinate with utilities to prevent brownouts.",
    },
    {
      issueId: "sig-005",
      whyItMatters: "Power failure during extreme heat is a cascading disaster. Loss of air conditioning, water pumps, and refrigeration creates immediate danger.",
      whoIsAffected: "15,000 residents across District 7, plus hospitals, schools, and water treatment facilities.",
      likelyNextImpact: "Rolling brownouts within 6 hours, potential full outage within 12. Hospital backup systems will be stressed to capacity.",
      urgencyExplanation: "Grid failure during heat events has historically led to multi-day outages with fatalities. Proactive load management is critical.",
      recommendation: "Implement voluntary load reduction. Coordinate with hospital for priority service. Prepare emergency generator deployment.",
    },
    {
      issueId: "sig-003",
      whyItMatters: "Waste accumulation creates health hazards through pest attraction and bacterial growth, especially dangerous during extreme heat.",
      whoIsAffected: "320 residents in Riverside Apartments, Block C, plus adjacent properties affected by odor and pests.",
      likelyNextImpact: "Health code violations within 48 hours. Pest infestation spreading to neighboring blocks. Resident complaints escalating.",
      urgencyExplanation: "While not immediately life-threatening, waste buildup during heat events accelerates health risks significantly.",
      recommendation: "Arrange emergency pickup within 24 hours. Distribute sealed waste bags. Schedule pest control treatment.",
    },
    {
      issueId: "sig-004",
      whyItMatters: "Traffic delays increase emergency response times and heat exposure for commuters and pedestrians.",
      whoIsAffected: "4,500 daily commuters, plus emergency vehicles needing arterial access.",
      likelyNextImpact: "Emergency response times increase by 8-12 minutes. Heat exposure incidents rise among stuck motorists.",
      urgencyExplanation: "Traffic congestion during heat events compounds health risks and hampers emergency response.",
      recommendation: "Coordinate with utility to accelerate or pause work during peak heat hours. Deploy traffic management personnel.",
    },
  ],
  "flood-traffic": [
    {
      issueId: "sig-010",
      whyItMatters: "Flash flooding is the #1 cause of weather-related fatalities. Rising water levels will inundate homes within 2 hours.",
      whoIsAffected: "3,100 residents in low-lying zones, including 400 households with children and 150 mobility-impaired individuals.",
      likelyNextImpact: "Water reaching residential foundations within 2 hours. Sewage backup into homes likely. Evacuation will be needed.",
      urgencyExplanation: "Flood waters rise exponentially. Delayed evacuation traps people in their homes.",
      recommendation: "Issue immediate evacuation order for low-lying zones. Deploy sandbags and pumps. Open emergency shelter.",
    },
    {
      issueId: "sig-011",
      whyItMatters: "Underpass flooding creates deadly trap conditions. 18 inches of water can sweep away vehicles.",
      whoIsAffected: "8,000 highway users, plus emergency vehicles that cannot reach flooded zones.",
      likelyNextImpact: "Stranded motorists requiring rescue. Emergency access to flood zone cut off.",
      urgencyExplanation: "Every minute the underpass remains open risks lives. Immediate closure and detour needed.",
      recommendation: "Close underpass immediately. Deploy barricades. Activate alternate route plan.",
    },
    {
      issueId: "sig-013",
      whyItMatters: "Medical campus power instability threatens critical care equipment and patient safety.",
      whoIsAffected: "5,200 staff and patients at the medical campus, including ICU patients on life support.",
      likelyNextImpact: "Backup generators will exhaust fuel within 3 hours. Patient transfer to alternate facilities needed.",
      urgencyExplanation: "Medical power failure is a direct threat to life. No room for delay.",
      recommendation: "Priority fuel delivery to generators. Begin patient transfer coordination. Alert receiving hospitals.",
    },
    {
      issueId: "sig-012",
      whyItMatters: "Storm debris blocks emergency access and impairs mobility for disabled residents.",
      whoIsAffected: "600 residents on Elm Street, including 85 mobility-impaired individuals and 12 wheelchair users.",
      likelyNextImpact: "Emergency vehicles unable to access Block 5. Disabled residents trapped.",
      urgencyExplanation: "Accessibility barriers during emergencies can be life-threatening for vulnerable populations.",
      recommendation: "Deploy debris removal crew within 4 hours. Conduct wellness checks on mobility-impaired residents.",
    },
  ],
  "blackout-medical": [
    {
      issueId: "sig-021",
      whyItMatters: "Patients mid-dialysis cannot be safely disconnected without risk of cardiac arrest. 12 lives depend on continuous power.",
      whoIsAffected: "12 dialysis patients, 8 medical staff, and families awaiting patient outcomes.",
      likelyNextImpact: "Generator fuel exhaustion in 3 hours. Without power, dialysis machines stop. Patient transfer to powered facility is the only option.",
      urgencyExplanation: "This is the most time-critical issue. Every minute without a plan increases patient risk.",
      recommendation: "Immediately begin patient transfer to South Campus medical center. Request emergency fuel delivery. Alert EMS for patient transport.",
    },
    {
      issueId: "sig-020",
      whyItMatters: "Campus-wide blackout affects all operations: lighting, HVAC, elevators, communications, security systems.",
      whoIsAffected: "9,500 students, faculty, and staff across North Campus.",
      likelyNextImpact: "Building temperatures rising. Elevator entrapments likely. Security systems offline. Student confusion and anxiety.",
      urgencyExplanation: "Campus blackout affects safety systems across all buildings. Coordinated response is essential.",
      recommendation: "Activate emergency communication system. Lock non-essential buildings. Deploy safety personnel to each building.",
    },
    {
      issueId: "sig-022",
      whyItMatters: "Without water pressure, sanitation and hydration are compromised across 4 major housing buildings.",
      whoIsAffected: "2,200 students in housing blocks A-D, including international students unfamiliar with campus resources.",
      likelyNextImpact: "Sanitation facilities non-functional above 3rd floor. Water distribution points needed.",
      urgencyExplanation: "Water loss in dormitories creates immediate sanitation and health risks.",
      recommendation: "Deploy water distribution points at each building entrance. Coordinate with dining services for bottled water.",
    },
    {
      issueId: "sig-023",
      whyItMatters: "Rising indoor temperatures during a blackout create heat stress conditions, especially for elderly summer program participants.",
      whoIsAffected: "450 summer program residents, including 80 elderly participants.",
      likelyNextImpact: "Indoor temperatures will reach dangerous levels within 3-4 hours. Evacuation may be needed.",
      urgencyExplanation: "Without HVAC, building temperatures will become unsafe. Proactive cooling measures are essential.",
      recommendation: "Open windows for ventilation. Deploy fans from emergency supplies. Identify cooler buildings for temporary relocation.",
    },
  ],
};

// ─── Pre-computed Response Plans ───
export const DEMO_RESPONSE_PLANS: Record<string, ResponsePlan[]> = {
  "heatwave-water": [
    {
      issueId: "sig-002",
      immediateAction: "Deploy emergency water tankers to zones 4A and 4B within 1 hour. Set up distribution points at community centers.",
      recommendedTeam: "Water Operations + Emergency Services",
      requiredResources: ["3 water tankers", "500 emergency water jugs", "6 distribution staff", "Boil-water advisory notice"],
      thirtyMinutePlan: "Dispatch water tankers. Activate community center distribution points. Issue boil-water advisory via emergency alert system. Notify hospitals and nursing homes.",
      twentyFourHourNote: "Complete pressure assessment of zone 4A/4B infrastructure. Coordinate with regional water authority for supplemental supply. Begin repair assessment.",
      residentInstructions: "1. Collect emergency water from nearest distribution point. 2. Boil all tap water before drinking. 3. Limit water use to drinking and hygiene. 4. Report any sewage backup immediately.",
      escalationThreshold: "If pressure drops below 20% or full outage occurs, escalate to district emergency management. Request state water emergency declaration.",
    },
    {
      issueId: "sig-001",
      immediateAction: "Open 5 cooling centers across District 7. Begin wellness checks for 2,100 identified elderly residents.",
      recommendedTeam: "Community Services + Public Health",
      requiredResources: ["5 cooling center locations", "20 wellness check volunteers", "Medical response standby", "Emergency notification system"],
      thirtyMinutePlan: "Activate cooling centers. Deploy wellness check teams. Issue heat emergency public advisory. Coordinate with hospitals for surge capacity.",
      twentyFourHourNote: "Monitor heat-related emergency calls. Maintain cooling center operations. Continue wellness check rounds every 4 hours.",
      residentInstructions: "1. Stay indoors during peak heat (11am-6pm). 2. Visit nearest cooling center if you lack air conditioning. 3. Drink water every 30 minutes even if not thirsty. 4. Check on elderly neighbors.",
      escalationThreshold: "If heat-related ER visits exceed 50 in 6 hours, request state emergency declaration and National Guard support.",
    },
  ],
  "flood-traffic": [
    {
      issueId: "sig-010",
      immediateAction: "Issue immediate evacuation order for Willow Creek Basin. Deploy sandbags and pumps to protect residential foundations.",
      recommendedTeam: "Emergency Services + Fire Department",
      requiredResources: ["Evacuation buses (5)", "Sandbags (2,000)", "Water pumps (4)", "Emergency shelter setup"],
      thirtyMinutePlan: "Activate evacuation sirens. Deploy sandbag barriers. Open emergency shelter at Lincoln High. Begin door-to-door checks in low-lying areas.",
      twentyFourHourNote: "Monitor water levels continuously. Maintain shelter operations. Begin damage assessment once waters recede. Coordinate with Red Cross.",
      residentInstructions: "1. Evacuate immediately if in low-lying zone. 2. Move vehicles to higher ground. 3. Do not walk or drive through floodwater. 4. Bring medications and important documents.",
      escalationThreshold: "If water rises above 3 feet or structural damage is observed, escalate to state emergency management. Request National Guard support.",
    },
    {
      issueId: "sig-011",
      immediateAction: "Close Highway 101 underpass immediately. Deploy barricades and activate emergency detour route via Cedar Boulevard.",
      recommendedTeam: "Traffic Management + Highway Patrol",
      requiredResources: ["Barricades (20)", "Traffic cones (50)", "Electronic message signs (3)", "4 traffic officers"],
      thirtyMinutePlan: "Close both directions of underpass. Activate detour signs. Deploy officers to direct traffic. Notify navigation apps of closure.",
      twentyFourHourNote: "Monitor water levels. Coordinate with drainage crews. Estimate reopening time. Maintain detour until safe.",
      residentInstructions: "1. Avoid Highway 101 underpass. 2. Use Cedar Boulevard detour. 3. Allow extra travel time. 4. Do not attempt to drive through standing water.",
      escalationThreshold: "If water reaches 24 inches or nearby roads flood, expand closure radius and activate regional traffic rerouting.",
    },
    {
      issueId: "sig-013",
      immediateAction: "Priority fuel delivery to medical campus generators. Begin patient transfer coordination with South Bay Medical Center.",
      recommendedTeam: "Medical Operations + Emergency Services",
      requiredResources: ["Fuel tanker (1)", "Ambulance support (3)", "Patient transfer records", "Backup generator fuel (500 gal)"],
      thirtyMinutePlan: "Dispatch fuel tanker to medical campus. Contact South Bay Medical for capacity. Begin ICU patient transfer. Maintain critical care on generators.",
      twentyFourHourNote: "Complete patient transfers if power not restored. Assess equipment status. Coordinate with utility for restoration timeline.",
      residentInstructions: "1. If you are a patient, follow medical staff instructions. 2. Do not leave the building unless directed. 3. Keep mobile devices charged. 4. Report any equipment issues immediately.",
      escalationThreshold: "If fuel supply cannot be secured within 2 hours or generator failure is imminent, activate mass casualty protocol.",
    },
  ],
  "blackout-medical": [
    {
      issueId: "sig-021",
      immediateAction: "Begin emergency patient transfer from dialysis center to South Campus medical center. Request emergency fuel delivery for backup generators.",
      recommendedTeam: "Medical Emergency Team + EMS",
      requiredResources: ["Ambulances (4)", "Portable dialysis equipment", "Fuel for generators (300 gal)", "Patient transport staff (8)"],
      thirtyMinutePlan: "Begin patient transfer one at a time. Maintain generator power for remaining patients. Contact South Campus for bed availability. Alert receiving nephrologists.",
      twentyFourHourNote: "Complete all patient transfers. Assess generator fuel status. Coordinate with power utility for restoration timeline. Document patient conditions.",
      residentInstructions: "1. Dialysis patients: remain calm, medical staff are transferring you safely. 2. Follow nurse instructions exactly. 3. Bring personal medications. 4. Family members: wait in designated area.",
      escalationThreshold: "If generator fuel drops below 1 hour or patient condition deteriorates, activate mass transfer protocol and request helicopter evacuation.",
    },
    {
      issueId: "sig-020",
      immediateAction: "Activate campus emergency communication system. Deploy safety personnel to each building. Lock non-essential buildings.",
      recommendedTeam: "Campus Safety + Facilities Management",
      requiredResources: ["Emergency radios (30)", "Battery-powered megaphones (10)", "Flashlights (100)", "Safety personnel (20)"],
      thirtyMinutePlan: "Broadcast emergency notification. Deploy safety teams to all buildings. Check elevator status. Secure chemistry labs and hazardous areas.",
      twentyFourHourNote: "Maintain building security. Monitor temperature in enclosed spaces. Coordinate with utility for restoration. Prepare contingency plans for extended outage.",
      residentInstructions: "1. Stay in your current building unless directed to evacuate. 2. Use stairs, not elevators. 3. Conserve phone battery. 4. Report any emergencies to campus safety.",
      escalationThreshold: "If outage exceeds 4 hours or building temperatures exceed 90°F, initiate partial evacuation to outdoor assembly points.",
    },
    {
      issueId: "sig-022",
      immediateAction: "Deploy water distribution points at each housing building entrance. Coordinate with dining services for bottled water supply.",
      recommendedTeam: "Housing Services + Dining Operations",
      requiredResources: ["Water jugs (500)", "Bottled water cases (200)", "Distribution tables (8)", "Staff volunteers (16)"],
      thirtyMinutePlan: "Set up distribution points. Begin bottled water distribution. Activate portable sanitation units. Check water pressure in each building.",
      twentyFourHourNote: "Maintain water distribution. Monitor sanitation needs. Coordinate with municipal water authority. Assess pump repair timeline.",
      residentInstructions: "1. Collect water from building entrance distribution point. 2. Use bottled water for drinking. 3. Limit toilet flushing. 4. Report any sewage issues immediately.",
      escalationThreshold: "If water pressure is not restored in 12 hours or sanitation becomes critical, activate building relocation protocol.",
    },
  ],
};

// ─── Impact Summary (demo) ───
export const DEMO_IMPACT_SUMMARY: Record<string, ImpactSummary> = {
  "heatwave-water": {
    topPriorities: [
      "Restore water pressure to zones 4A/4B immediately",
      "Deploy cooling centers and wellness checks",
      "Prevent grid failure through load management",
    ],
    affectedGroups: [
      "8,200 households without adequate water",
      "12,400 residents in extreme heat",
      "2,100 elderly residents at highest risk",
      "320 residents affected by waste buildup",
    ],
    readinessLevel: "Partial – critical gaps in water supply and cooling capacity",
    actionCoverage: 40,
    unresolvedRisks: 3,
    expectedCommunityImpact: "If actions are taken within the next 2 hours, we can prevent an estimated 15-20 heat-related hospitalizations and maintain water service for 80% of affected households.",
    decisionsMadeFaster: "PulseGrid identified the water outage as the #1 priority over heat advisory due to compounding risk – saving an estimated 45 minutes of assessment time.",
  },
  "flood-traffic": {
    topPriorities: [
      "Evacuate low-lying residential zones immediately",
      "Close and barricade Highway 101 underpass",
      "Secure medical campus power supply",
    ],
    affectedGroups: [
      "3,100 residents in flood zone",
      "8,000 highway commuters",
      "5,200 medical campus staff and patients",
      "600 residents blocked by storm debris",
    ],
    readinessLevel: "Emergency – active evacuation required",
    actionCoverage: 75,
    unresolvedRisks: 1,
    expectedCommunityImpact: "Immediate evacuation of 3,100 residents can prevent flood-related injuries. Power stabilization at medical campus protects critical care patients.",
    decisionsMadeFaster: "PulseGrid ranked flood evacuation above medical power issues due to time-to-impact analysis – enabling faster resource allocation.",
  },
  "blackout-medical": {
    topPriorities: [
      "Transfer dialysis patients to powered facility immediately",
      "Establish campus emergency communication",
      "Deploy water distribution and cooling measures",
    ],
    affectedGroups: [
      "12 dialysis patients in immediate danger",
      "9,500 campus community members",
      "2,200 students without water",
      "450 residents in rising heat",
    ],
    readinessLevel: "Critical – life-safety issue active",
    actionCoverage: 75,
    unresolvedRisks: 1,
    expectedCommunityImpact: "Immediate patient transfer protects 12 lives. Campus-wide coordination prevents secondary casualties from heat, dehydration, or falls.",
    decisionsMadeFaster: "PulseGrid identified the dialysis center as the #1 priority over the campus-wide blackout due to immediate life-safety threat – saving critical decision time.",
  },
};
